{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Resumen teoría para el Parcial Integrador - Introduccion a la Programacion (Primer Cuatrimestre 2023)\n",
    "\n",
    "Para un resumen mas completo ver: \n",
    "- [Apunte Luloide](https://yielding-eyeliner-2a6.notion.site/9bd81790733c47bdb6162a3989ffc236?v=7504303d05bb4b86910f032f33b540c4)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 1: Introduccion\n",
    "\n",
    "#### Conceptos\n",
    "\n",
    "> <b>Algoritmo</b>: Un algoritmo es la descripcion de los pasos precisos para resolver un problema a partir de datos de entrada adecuados.\n",
    "\n",
    "> <b>Programa</b>: Un programa es la descripcion de un algoritmo en un lenguaje de programacion (implementacion de un algoritmo).\n",
    "\n",
    "#### Especificacion (contrato):\n",
    "* Concepto: es un contrato que define que se debe resolver y que propiedades debe tener la solucion.\n",
    "* Partes de una especificacion:\n",
    "    * Encabezado.\n",
    "    * <b>Precondicion (requiere)</b>: Describen todas las condiciones y posibles valores o casuisticas de los parametros de entrada.\n",
    "    * <b>Poscondicion (asegura)</b>: Describen todas las condiciones y posibles valores o casuisticas de los parametros de salida y entrada/salida en funcion de los parametros de entrada.\n",
    "\n",
    "#### Lenguaje Formal != Lenguaje Natural"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 2: Logica\n",
    "\n",
    "#### Formulas, Simbolos y Variables proposicionales\n",
    "\n",
    "> Formulas: Son los True, False y las variables proposicionales con sus operaciones validas.\n",
    "\n",
    "> Simbolos: $\\rightarrow, \\exists, \\forall$\n",
    "\n",
    "> Variables Proposicionales: $p, q, ...$\n",
    "\n",
    "#### Relacion de fuerza entre formulas.\n",
    "> Decimos que $A$ es mas fuerte que $B$ cuando $A \\rightarrow B$ es tautologia\n",
    "\n",
    "#### Equivalencias entre formulas:\n",
    "\n",
    "1. Idempotencia:\n",
    "* $(p∧p) ↔p$ <br>\n",
    "* $(p∨p) ↔p$\n",
    "\n",
    "2. Asociatividad:\n",
    "* $(p∧q)∧r ↔ p∧(q∧r)$ <br>\n",
    "* $(p∨q)∨r ↔ p∨(q∨r)$\n",
    "\n",
    "3. Conmutatividad:\n",
    "* $(p∧q) ↔(q∧p)$ <br>\n",
    "* $(p∨q) ↔(q∨p)$\n",
    "\n",
    "4. Distributividad:\n",
    "* $p∧(q∨r) ↔ (p∧q)∨(p∧r)$<br>\n",
    "* $p∨(q∧r) ↔ (p∨q)∧(p∨r)$\n",
    "\n",
    "5. Reglas de De Morgan:\n",
    "* $¬(p∧q) ↔ ¬p ∨ ¬q$ <br>\n",
    "* $¬(p∨q) ↔ ¬p ∧ ¬q$\n",
    "\n",
    "#### Tipos de formulas:\n",
    "> <b>Tautologia</b>:  Una formula es una tautologia si siempre toma el valor V para valores definidos de sus variables proposicionales.\n",
    "\n",
    "> <b>Contradiccion</b>: Una formula es una contradiccion si siempre toma el valor F para valores definidos de sus variables proposicionales.\n",
    "\n",
    "> <b>Contingencia</b>: Cuando no es ni tautologia ni contradiccion.\n",
    "\n",
    "#### Diferencia Sematinca Clasica y Semantica Trivaluada ~ Cortocircuito \n",
    "* Se llama tambien secuencial porque se lee de izquierda a derecha, y termina cuando ya puede deducir el valor de la expresión\n",
    "* Se nota con una L en el subíndice (Ej: $\\rightarrow_L$)\n",
    "\n",
    "#### Cuantificadores ($\\forall, \\exists$)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 3: Especificacion\n",
    "\n",
    "#### Sobre-especificacion y Subespecificacion\n",
    "\n",
    "> <b>Sobre-especificacion</b>: Consiste en dar una postcondicion mas restrictiva de la que se necesita, o bien dar una precondicion mas laxa. Limita los posibles algoritmos que resuelven el problema, porque impone mas condiciones para la salida, o amplıa los datos de entrada.\n",
    "\n",
    "> <b>Sub-especificacion</b>: Consiste en dar una precondicion mas restrictiva de lo realmente necesario, o bien una postcondicion mas debil de la que se necesita. Deja afuera datos de entrada o ignora condiciones necesarias para la salida (permite soluciones no deseadas).\n",
    "\n",
    "#### Tipos de datos: Son conjuntos de datos con operaciones asociadas.\n",
    "\n",
    "#### Observaciones sobre tipos de datos: \n",
    "* Para char se asume que $ord('b') = ord('a') + 1$\n",
    "* Las uplas admiten != tipos\n",
    "* Las secuencias solo son de un tipo\n",
    "* Tipos de dato Enum...\n",
    "    * enum Semana { lunes, martes, miercoles, ... }\n",
    "\n",
    "#### Nocion de predicados y modularizacion\n",
    "\n",
    "#### Condicionales en la especificacion:\n",
    "> res = if (condicion) then (opcionTrue) else (opcionFalse) fi"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 4: Buenas Practicas\n",
    "\n",
    "### Nociones de...\n",
    "\n",
    "#### Paradigmas de la Programacion\n",
    "\n",
    "* <b>Paradigma Declarativo</b>: Son lenguajes donde el programador le indicara a la maquina lo que quiere hacer y el resultado que desea, pero no necesariamente el como hacerlo. Describe un conjunto de condiciones, proposiciones, afirmaciones, restricciones, ecuaciones o transformaciones que describen el problema y detallan su solucion.\n",
    "    * <b>Logico</b>: Los programas estan construıdos unicamente por expresiones logicas (es decir, son Verdaderas o Falsas)\n",
    "    * <b>Funcional</b>: Esta basado en el modelo matematico de composicion funcional. El resultado de un calculo es la entrada del siguente, y ası sucesivamente hasta que una composicion produce el valor deseado.\n",
    "\n",
    "* <b>Paradigma Imperativo</b>: Describe la programacion como una secuencia de instrucciones o comandos que cambian el estado de un programa.\n",
    "    * <b>Estructurado</b>: los programas se dividen en bloques (procedimientos y funciones), que pueden o no comunicarse entre sı. Existen estructuras de control, que dirigen el flujo de ejecucion: IF, GO TO, Ciclos, etc\n",
    "    * <b>Orientado a Objetos</b>: Se basa en la idea de encapsular estado y comportamiento en objetos. Los objetos son entidades que se comunican entre sı por medio de mensajes\n",
    "\n",
    "Existen lenguajes multiparadigma:\n",
    "\n",
    "#### Buenas Practicas:\n",
    "\n",
    "* Los comentarios no tapan mal codigo,\n",
    "* No hacer chistes en el codigo :(,\n",
    "* Modularizacion: Encapsular comportamiento en funciones auxiliares, de modo que queden funciones \"chicas\" (70 lineas como mucho),\n",
    "* Convenciones en nombres,\n",
    "* Mismo estilo de codigo,\n",
    "* Formato vertical (archivos no muy grandes),\n",
    "* Codigo homogeneo,\n",
    "* Desarrollo incremental: Escribir bloques pequenos y testeables de funcionalidad, teniendo en todo momento una aplicacion (parcialmente) funcional,\n",
    "* Etc, etc.\n",
    "\n",
    "\n",
    "#### Metricas de Complejidad:\n",
    "\n",
    "> Cyclomatic Complexity: Se calcula a partir del control-flow graph.\n",
    "\n",
    "> Cognitive Complexity: Es una metrica que se utiliza para aproximar la dificultad para que un ser humano entienda un programa (por ruptura de la linealidad de la lectura del codigo)\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 5: Programacion Funcional\n",
    "\n",
    "#### Concepto de ecuacion orientada\n",
    "\n",
    "* Reduccion: de izquierda a derecha.\n",
    "* Redex: expresion a reducir.\n",
    "\n",
    "#### Tipos de funciones\n",
    "\n",
    "> Funciones Totales: Nunca se indefinen\n",
    "\n",
    "> Funciones Parciales: Hay argumentos para los cuales se indefinen\n",
    "\n",
    "#### Transparencia referencial: \n",
    "Es la propiedad de un lenguaje que garantiza que el valor de una expresion depende exclusivamente de sus subexpresiones. Por lo tanto, cada expresion del lenguaje representa siempre el mismo valor en cualquier lugar de un programa.\n",
    "\n",
    "#### Polimorfismo:\n",
    "Se llama polimorfismo a una funcion que puede aplicarse a distintos tipos de datos (sin redefinirla).\n",
    "\n",
    "\n",
    "#### Saber programar en Haskell (notacion curry, notacion prefija e infija, clases de tipo para operaciones...)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 6: Recursion en $\\Z$\n",
    "\n",
    "#### Saber usar recursion en Haskell...\n",
    "\n",
    "Hallar bien los casos base e identificar el paso inductivo."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 7: Recursion en Listas\n",
    "\n",
    "#### Saber usar recursion de listas en Haskell...\n",
    "* Operaciones (:) y ++ \n",
    "* Conjuntos como <code len=\"haskell\"> type Set a = [a] </code>"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 8: Validacion y Verificacion (V&V)\n",
    "\n",
    "#### Control de calidad de software\n",
    "\n",
    "V&V deberıa aplicarse en cada instancia del proceso de desarrollo.\n",
    "\n",
    "> <b>Validacion</b>: ¿Estamos haciendo el producto correcto? El software deberıa hacer lo que el usuario requiere de el.\n",
    "\n",
    "> <b>Verificacion</b>: ¿Estamos haciendo el producto correctamente? El software deberıa realizar lo que su especificacion indica.\n",
    " \n",
    "#### Error $\\rightarrow$ Defecto $\\rightarrow$ Falla\n",
    "\n",
    "> <b>Error</b>: Equivocacion humana.\n",
    "\n",
    "> <b>Defecto</b>: Desperfecto en algun componente del sistema (en el texto del programa, una especificacion, un diseño, etc), que origina una o mas fallas.\n",
    "\n",
    "> <b>Falla</b>: Diferencia entre los resultados esperados y reales.\n",
    "\n",
    "#### Objetivos V&V:\n",
    "* Hallar defectos\n",
    "* Asegurar que respeca especificacion\n",
    "* Asegurar que satisface necesidades de usuarios\n",
    "\n",
    "#### Tipos de V&V\n",
    "\n",
    "* <b>Estatica</b>: trata con el analisis de una representacion estatica del sistema para descubrir problemas.\n",
    "\n",
    "* <b>Dinamica</b>: trata con ejecutar y observar el comportamiento de un producto (ej. testing)\n",
    "\n",
    "#### V&V Dinamica por Testing:\n",
    "\n",
    "> <b>Testing</b>: Es el proceso de ejecutar un producto para:\n",
    ">> [1] Verificar que satisface los requerimientos (en nuestro caso, la especificacion) <br>\n",
    ">> [2] Identificar diferencias entre el comportamiento real y el comportamiento esperado. <br>\n",
    "Es decir, iene como objetivo encontrar defectos en el software. Representa entre el 30 % al 50 % del costo de un software confiable.\n",
    "\n",
    "#### Niveles de testing:\n",
    "> <b>Test de Sistema</b>: Test de todo el sistema (por lo general, de aceptacion).\n",
    "\n",
    "> <b>Test de Integracion</b>: Esta orientado a verificar que las partes de un sistema que funcionan bien aisladamente,\n",
    "tambien lo hacen en conjunto (testeamos la interaccion entre las partes).\n",
    "\n",
    "> <b>Test de Unidad</b>: Se realiza sobre una unidad de codigo pequena, claramente definida.\n",
    "\n",
    "#### Conceptos del testing:\n",
    "> <b>Test Input (o dato de prueba)</b>: Es una asignaci ́on concreta de valores a los parametros de entrada para ejecutar el programa bajo test.\n",
    "\n",
    "> <b>Test Case (o caso de prueba)</b>: Es un programa que ejecuta el programa bajo test usando un dato de test, y chequea (automaticamente) si se cumple la condicion de aceptacion sobre la salida del programa bajo test.\n",
    "\n",
    "> <b>Test Suite</b>: Es un conjunto de casos de Test (o de conjunto de casos de prueba).\n",
    "\n",
    "#### Limitaciones del Testing:\n",
    "Al no ser exhaustivo, el testing NO puede probar (demostrar) que el software funciona correctamente.\n",
    "\n",
    "Una de las mayores dificultades es encontrar un conjunto de tests\n",
    "adecuado:\n",
    "* Suficientemente grande para abarcar el dominio y maximizar la probabilidad de encontrar errores.\n",
    "* Suficientemente peque ̃no para poder ejecutar el proceso con cada elemento del conjunto y minimizar el costo del testing.\n",
    "\n",
    "#### Criterios para seleccionar test input:\n",
    "* <b>Caja Blanca</b>: los casos de test se generan analizando la implementacion para determinar los casos de test.\n",
    "* <b>Caja Negra</b>: los casos de test se generan analizando la especificacion sin considerar la implementacion.\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 9: Caja Negra\n",
    "\n",
    "#### Metodo de Particion de Categorias:\n",
    "\n",
    "Es una tecnica para generar casos de prueba de una manera metodica.\n",
    "\n",
    "* Paso 1: Listar todos los programas a testear.\n",
    "* Paso 2: Elegir un programa de la lista,\n",
    "    * Paso 3: Identificar los factores (sus parametros y relaciones)\n",
    "    * Paso 4: Determinar las categorias (caracteristicas relevantes) de cada factor.\n",
    "    * Paso 5: Determinar las choices por cada categoria de cada factor.\n",
    "    * Paso 6: Clasificar las choices: errores unicos, restricciones, etc.\n",
    "    * Paso 7: Armar casos de prueba combinando distintas elecciones para cada categoria y detallando el resultado esperado de c/u.\n",
    "    * Paso 8: Volver al paso 2 hasta testear todos los programas.\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 10: Programacion Imperativa\n",
    "\n",
    "#### Tipos de pasaje de parametros:\n",
    "* <b>IN</b>: Al salir de la funcion o procedimiento, la variable pasada como parametro continuara teniendo su valor original.\n",
    "\n",
    "* <b>OUT</b>: Al salir de la funcion o procedimiento, la variable pasada como parametro tendra un nuevo valor asignado dentro de dicha funcion o procedimiento. Su valor inicial no importa ni deberıa ser leıdo dentro de la funci ́on o procedimiento en cuestion.\n",
    "\n",
    "* <b>INOUT</b>: Al salir de la funcion o procedimiento, la variable pasada como parametro tendra un nuevo valor asignado dentro de dicha funci ́on o procedimiento. Su valor inicial SI importa dentro de la funcion o procedimiento en cuestion.\n",
    "\n",
    "#### Pasajes de parametros en Python:\n",
    "* <b>REFERENCIA</b>: Tipos compuestos y estructuras (listas, etc): se pasan por referencia.\n",
    "* <b>VALOR</b>: Tipo primitivos (int, char, strings, etc) se pasan por valor.\n",
    "\n",
    "#### Funcion != Procedimiento\n",
    "* Funcion $\\rightarrow$ Devuelve un valor\n",
    "* Procedimiento $\\rightarrow$ No devuelve nada\n",
    "\n",
    "#### Saber programar en Python\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 11: Scope de variables y estructuras\n",
    "\n",
    "#### Scope de variables (Python distingue 4 niveles de visibilidad o alcance): \n",
    "* <b>Local</b>: corresponde al ́ambito de una funcion.\n",
    "* <b>No local o Enclosed</b>: no esta en el ambito local, pero aparece en una funcion que reside dentro de otra funcion.\n",
    "* <b>Global</b>: declarada en el cuerpo principal del programa, fuera de cualquier funcion.\n",
    "* <b>Integrado o Built-in</b>: son todas las declaraciones propias de Python (por ejemplo: def, print, etc)\n",
    "\n",
    "#### Saber controles de flujo en python \n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 12: Arrays y Listas\n",
    "\n",
    "#### Arrays:\n",
    "* Secuencias de una cantidad fija de valores del mismo tipo.\n",
    "* Longitud fija \n",
    "* Mismo tipo\n",
    "* Los elementos se obtienen por index y no secuencialmente\n",
    "\n",
    "Ejemplo de la libreria que usan...\n",
    "\n",
    "<code>\n",
    "from array import *\n",
    "a: array = array('i', [1,2,3,1])\n",
    "a.count(1) # da 2 porque hay dos unos en a\n",
    "</code>\n",
    "\n",
    "\n",
    "#### Listas:\n",
    "* Longitud dinamica\n",
    "* Pueden tener distintos tipos de datos\n",
    "* En python son un tipo de array\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 13: TADS\n",
    "\n",
    "#### Tipo Abstracto de Datos (TADS): \n",
    "* Definicion: Un Tipo Abstracto de Datos (TAD) es un modelo que define valores y las operaciones que se pueden realizan sobre ellos.\n",
    "* Se denomina abstracto ya que la intencion es que quien lo utiliza, no necesita conocer los detalles de la representacion interna o bien el como estan implementadas sus operaciones.\n",
    "\n",
    "\n",
    "#### Pila: \n",
    "\n",
    "<code> from queue import LifoQueue as Pila </code>\n",
    "\n",
    "* Definicion: Son listas LIFO (Last In - First Out / el ultimo que entra es el primero que sale)\n",
    "\n",
    "#### Cola:\n",
    "\n",
    "<code> from queue import Queue as Cola </code>\n",
    "\n",
    "* Definicion: Son listas FIFO (First In - First Out / el primero que entra es el primero que sale)\n",
    "\n",
    "#### Metodos (en ambas):\n",
    "* get\n",
    "* put\n",
    "* empty\n",
    "\n",
    "#### Diccionario:\n",
    "\n",
    "Un diccionario es una estructura de datos que permite almacenar y organizar pares clave-valor.\n",
    "* Las claves deben ser inmutables (como cadenas de texto, numeros, etc), mientras que los valores pueden ser de cualquier tipo de dato.\n",
    "* La clave actua como un identificador  ́unico para acceder a su valor correspondiente.\n",
    "* Los diccionarios son mutables, lo que significa que se pueden modificar agregando, eliminando o actualizando elementos.\n",
    "* No ordenados: Los elementos dentro de un diccionario no tienen un orden espec ́ıfico. No se garantiza que se mantenga el orden de insercion de los elementos.\n",
    "\n",
    "#### Manejo de Archivos en Python\n",
    "\n",
    "#### Nocion de API"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Teorica 14: Caja Blanca\n",
    "\n",
    "#### Saber diagramar Control Flow Graph (CFG)\n",
    "\n",
    "#### Usos de Caja Blanca:\n",
    "* Complemento al Test de Caja Negra: permite encontrar mas casos o definir casos mas especificos\n",
    "* Como criterio de adecuacion del Test de Caja Negra: brinda herramientas que nos ayudar a determinar cuan bueno o confiable resultaron ser los test suites definidos.\n",
    "\n",
    "#### Criterios de Adecuacion Estructurales por CFG:\n",
    "\n",
    "* [a] Cubrimiento de Sentencias (nodos): \n",
    "    * Definicion: Cada bloque/sentencia/nodo debe ser ejecutado al menos 1 vez por algun test case.\n",
    "    * Cobertura: $\\frac{nodosEjercitados}{totalNodos}$\n",
    "    \n",
    "    <br>\n",
    "    \n",
    "* [b] Cubrimiento de Arcos (flechas):\n",
    "    * Definicion: Cada arco/flecha que une a los nodos debe ser ejecutada al menos 1 vez por algun test case.\n",
    "    * Observacion: El cubrimiento de todos los arcos implica cubrir todos los nodos.\n",
    "    * Cobertura: $\\frac{arcosEjercitados}{totalArcos}$\n",
    "    \n",
    "    <br>\n",
    "\n",
    "* [c] Cubrimiento de Decisiones (branches):\n",
    "    * Definicion: Todas las deciciones (los arcos True y False en el CFG) deben ser ejecutados por algun test suite.\n",
    "    * Cobertura: $\\frac{decisionesEjercitadas}{totalDeciciones}$\n",
    "    * Necesitan cobertura 100%\n",
    "    \n",
    "    <br>\n",
    "\n",
    "* [d] Cubrimiento de Condiciones Basicas:\n",
    "    * Definicion: Una condicion básica es una formula atómica (indivisible) que compone una division. \n",
    "    \n",
    "    * Cobertura: $\\frac{CantidadVariablesEvaluadasEnCadaCondicion}{2*CantidadCondicionesBasicas}$\n",
    "    * Necesitan cobertura 100%\n",
    "\n",
    "    * Ejemplo: Sea el condicional \"(($x=1 || y=2$) ^ len > 0)\", las condiciones basicas son...\n",
    "        * $x=1$\n",
    "        * $y=2$\n",
    "        * $len > 0$\n",
    "    \n",
    "    <br>\n",
    "\n",
    "* [e] Cubrimiento de Caminos:\n",
    "    * Definicion: Cada camino en el CFG debe ser transitado por al menos un test case.\n",
    "    * Cobertura: $\\frac{caminosTransitados}{cantidadCaminos}$\n",
    "    \n",
    "    <br>\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
